"""
OBSCURA Sourcing Engine — Automated Variant Stock Synchronization
==================================================================
Reads active storefront catalog items from products.js, resolves their 
private sourcing mappings in supplier_mappings.json, re-scrapes live 
stock states from Weidian, and updates the storefront database in place.

Can be run weekly as a cron schedule or triggered manually via CLI.
"""
import re
import json
import asyncio
import argparse
from datetime import datetime
from pathlib import Path
from bs4 import BeautifulSoup

# Setup local paths
BASE_DIR = Path(__file__).resolve().parent
STOREFRONT_DIR = BASE_DIR.parent / "storefront"
PRODUCTS_FILE = STOREFRONT_DIR / "src" / "data" / "products.js"
SUPPLIER_MAPPINGS_FILE = BASE_DIR / "supplier_mappings.json"

# Import sourcing agent
import sys
sys.path.append(str(BASE_DIR))
from chinese_sourcing_agent import ChineseSourcingAgent

def log(msg):
    ts = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    print(f"[{ts}] {msg}", flush=True)

def load_supplier_mappings():
    if SUPPLIER_MAPPINGS_FILE.exists():
        with open(SUPPLIER_MAPPINGS_FILE, "r", encoding="utf-8") as f:
            return json.load(f)
    return {}

def save_supplier_mappings(mappings):
    with open(SUPPLIER_MAPPINGS_FILE, "w", encoding="utf-8") as f:
        json.dump(mappings, f, indent=2, ensure_ascii=False)

def load_current_products():
    """Parse the current products.js file and return products array, collections raw, and outfits raw."""
    if not PRODUCTS_FILE.exists():
        log(f"[!] Storefront database not found at {PRODUCTS_FILE}")
        return [], "[]", "[]"
    
    content = PRODUCTS_FILE.read_text(encoding="utf-8")
    
    match = re.search(r'export const DEMO_PRODUCTS = (\[[\s\S]*?\]);', content)
    existing_products_raw = match.group(1) if match else "[]"
    
    try:
        existing_products = json.loads(existing_products_raw)
    except json.JSONDecodeError:
        existing_products = []
        
    coll_match = re.search(r'export const COLLECTIONS = (\[[\s\S]*?\]);', content)
    collections_raw = coll_match.group(1) if coll_match else "[]"
    
    outfits_match = re.search(r'export const DEMO_OUTFITS = (\[[\s\S]*?\]);', content)
    outfits_raw = outfits_match.group(1) if outfits_match else "[]"
    
    return existing_products, collections_raw, outfits_raw

def build_products_js(products, collections_raw, outfits_raw):
    lines = [
        "/**",
        " * Product catalog — Auto-generated by storefront_uploader.py",
        f" * Last updated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
        " */",
        "",
        "export const DEMO_PRODUCTS = " + json.dumps(products, indent=2) + ";",
        "",
        f"export const COLLECTIONS = {collections_raw};",
        "",
        f"export const DEMO_OUTFITS = {outfits_raw};",
        ""
    ]
    return "\n".join(lines)

async def sync_stock(product_id=None, dry_run=False):
    log("=" * 60)
    log("OBSCURA AUTOMATED VARIANT STOCK SYNC SYSTEM")
    log("=" * 60)
    
    # Load files
    products, collections_raw, outfits_raw = load_current_products()
    supplier_mappings = load_supplier_mappings()
    
    if not products:
        log("[!] No active products loaded. Exiting.")
        return
        
    log(f"[+] Loaded {len(products)} active products from storefront.")
    log(f"[+] Loaded {len(supplier_mappings)} private supplier mappings.")
    
    target_products = products
    if product_id:
        target_products = [p for p in products if p["id"] == product_id]
        if not target_products:
            log(f"[!] Specified product ID '{product_id}' not found in products.js.")
            return
            
    log(f"[*] Processing stock checks for {len(target_products)} target product(s)...")
    
    agent = ChineseSourcingAgent(headless=True)
    changes_made = 0
    
    for prod in target_products:
        p_id = prod["id"]
        mapping = supplier_mappings.get(p_id)
        if not mapping:
            log(f"  [SKIP] {p_id} — No supplier mapping found.")
            continue
            
        url = mapping.get("source_url")
        if not url:
            log(f"  [SKIP] {p_id} — No source_url mapped.")
            continue
            
        log(f"  [*] Re-scraping stock status for '{prod['name']}' ({p_id})")
        log(f"      Source URL: {url[:80]}...")
        
        try:
            # Execute headless scrape (generate_contact_sheet=False for speed)
            res = await agent.scrape_product(url, generate_contact_sheet=False)
            if not res or not isinstance(res, dict):
                log(f"    [!] Scraper failed to fetch results for {p_id}.")
                continue
                
            meta = res.get("metadata", {})
            new_stock = meta.get("stock_status", {})
            
            # Compare stock status changes
            old_stock = prod.get("stock_status", {})
            log(f"    - Current Stock Map: {old_stock}")
            log(f"    - New Sourced Stock Map: {new_stock}")
            
            stock_diffs = []
            all_keys = set(old_stock.keys()).union(set(new_stock.keys()))
            for key in all_keys:
                old_val = old_stock.get(key)
                new_val = new_stock.get(key)
                if old_val != new_val:
                    state_old = "IN STOCK" if old_val else "OUT OF STOCK"
                    state_new = "IN STOCK" if new_val else "OUT OF STOCK"
                    stock_diffs.append(f"      * Variant '{key}': {state_old} → {state_new}")
            
            if stock_diffs:
                log(f"    [!] Detected variant stock status changes:")
                for diff in stock_diffs:
                    print(diff)
                changes_made += 1
            else:
                log("    [OK] No changes in variant stock status.")
                
            if not dry_run:
                # Update products.js entry
                prod["stock_status"] = new_stock
                # Update supplier mappings entry
                mapping["stock_status"] = new_stock
                mapping["last_sync"] = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
                
        except Exception as e:
            log(f"    [ERROR] Failed to check stock for {p_id}: {e}")
            
    # Save results
    if changes_made > 0 and not dry_run:
        log("[*] Writing updated stock mapping to files...")
        save_supplier_mappings(supplier_mappings)
        products_content = build_products_js(products, collections_raw, outfits_raw)
        PRODUCTS_FILE.write_text(products_content, encoding="utf-8")
        log("[OK] products.js and supplier_mappings.json successfully updated!")
    elif dry_run:
        log("[DRY-RUN] Finished checks. No files modified.")
    else:
        log("[OK] Finished checks. All target products are fully up to date.")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="OBSCURA Weekly Stock Sync")
    parser.add_argument("--product", type=str, help="Specific product ID to sync")
    parser.add_argument("--dry-run", action="store_true", help="Perform checks without writing to files")
    args = parser.parse_args()
    
    # Run async function
    asyncio.run(sync_stock(product_id=args.product, dry_run=args.dry_run))
