import asyncio
import os
import glob
from gemini_director import GeminiDirector

async def run_test():
    print("Starting Smart Merge / Full Fit Test...")
    
    # 1. Get the products
    input_dir = "input_sourcing"
    product_images = sorted(glob.glob(os.path.join(input_dir, "*.png")))
    
    if len(product_images) < 2:
        print("[!] Need at least 2 products for a full fit test.")
        return
        
    print(f"[*] Found {len(product_images)} products to merge:")
    for p in product_images:
        print(f"    - {os.path.basename(p)}")
        
    # 2. Get the OFFICIAL Male Model sheets
    model_face = r"C:\Users\USER\.gemini\antigravity\brain\83a89fde-ace2-4259-9b25-28e931d346cb\official_male_face_sheet_1777644321778.png"
    model_body = r"C:\Users\USER\.gemini\antigravity\brain\83a89fde-ace2-4259-9b25-28e931d346cb\official_male_body_sheet_1777644429422.png"
    
    if not os.path.exists(model_face) or not os.path.exists(model_body):
        print("[!] Model sheets missing.")
        return
        
    # 3. Initialize Director
    director = GeminiDirector()
    
    print("\n[*] Consulting Gemini 2.5 Flash for Technical Multi-Reference Design...")
    result = await director.design_full_fit(product_images, model_face, model_body)
    
    if not result:
        print("[!] Director failed to design the shoot.")
        return
        
    print("\n==============================================")
    print(f" OUTFIT NAME: {result.get('fit_name', 'Unknown')}")
    print(f" LOCATION: {result.get('location', 'Unknown')}")
    print(f" LIGHTING: {result.get('lighting', 'Unknown')}")
    print(f" BUNDLE DISCOUNT: {result.get('suggested_bundle_discount', '0%')}")
    print("==============================================\n")
    
    print("STYLING NOTES:")
    print(result.get('styling_notes', 'None'))
    print("\nSHOT LIST (PROMPTS GENERATED BY GEMINI):")
    print(f"\n1. FRONT HERO:\n{result.get('full_fit_prompt', '')}")
    print(f"\n2. FLAT LAY:\n{result.get('flat_lay_prompt', '')}")
    
    # Let's save this plan to a file so the GenerationRouter can pick it up
    import json
    with open("smart_merge_plan.json", "w") as f:
        json.dump(result, f, indent=4)
        
    print("\n[+] Plan saved to smart_merge_plan.json. Ready to generate images.")

if __name__ == "__main__":
    asyncio.run(run_test())
