import json
from datetime import datetime
from unittest.mock import patch
from auto_stock_sync import build_products_js

def test_build_products_js():
    # Arrange
    products = [
        {"id": "prod1", "name": "Test Product 1"},
        {"id": "prod2", "name": "Test Product 2"}
    ]
    collections_raw = '[\n  { "id": "coll1" }\n]'
    outfits_raw = '[\n  { "id": "outfit1" }\n]'

    expected_time = datetime(2023, 10, 25, 12, 34, 56)
    expected_time_str = "2023-10-25 12:34:56"

    # Act
    with patch('auto_stock_sync.datetime') as mock_datetime:
        mock_datetime.now.return_value = expected_time
        mock_datetime.strftime = datetime.strftime

        result = build_products_js(products, collections_raw, outfits_raw)

    # Assert
    expected_lines = [
        "/**",
        " * Product catalog — Auto-generated by storefront_uploader.py",
        f" * Last updated: {expected_time_str}",
        " */",
        "",
        "export const DEMO_PRODUCTS = " + json.dumps(products, indent=2) + ";",
        "",
        f"export const COLLECTIONS = {collections_raw};",
        "",
        f"export const DEMO_OUTFITS = {outfits_raw};",
        ""
    ]
    expected_result = "\n".join(expected_lines)

    assert result == expected_result
